### ISSUE TITLE
在 linux(ubuntu) .net core 2.2 版本下，Face接口调用操作超时。

### ISSUE THREAD

**Issue by dogvane** [Baidu-AIP/dotnet-sdk#15]
在 linux(ubuntu) .net core 2.2 版本下，Face接口调用操作超时。
代码在window下正常。
网络访问正常，token能正常获得并输出。
单独wget api 地址，正常。

猜测，设置的某些入参会导致在linux下被卡到超时。

Token:24.2bea30dc9420de9075bfb5203d0f7615.2592000.1566562949.282335-16797556

System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at Baidu.Aip.AipServiceBase.SendRequetRaw(AipHttpRequest aipRequest) in /home/ubuntu/apps/code-server1.939-vsc1.33.1-linux-x64/dotnet/BilibiliAI/AipSdk/Baidu/Aip/AipServiceBase.cs:line 148
Baidu.Aip.AipException: The operation has timed out.
   at Baidu.Aip.AipServiceBase.SendRequetRaw(AipHttpRequest aipRequest) in /home/ubuntu/apps/code-server1.939-vsc1.33.1-linux-x64/dotnet/BilibiliAI/AipSdk/Baidu/Aip/AipServiceBase.cs:line 154
   at Baidu.Aip.AipServiceBase.SendRequet(AipHttpRequest aipRequest) in /home/ubuntu/apps/code-server1.939-vsc1.33.1-linux-x64/dotnet/BilibiliAI/AipSdk/Baidu/Aip/AipServiceBase.cs:line 137
   at Baidu.Aip.AipServiceBase.PostAction(AipHttpRequest aipReq) in /home/ubuntu/apps/code-server1.939-vsc1.33.1-linux-x64/dotnet/BilibiliAI/AipSdk/Baidu/Aip/AipServiceBase.cs:line 102
   at Baidu.Aip.Face.Face.Search(String image, String imageType, String groupIdList, Dictionary`2 options) in /home/ubuntu/apps/code-server1.939-vsc1.33.1-linux-x64/dotnet/BilibiliAI/AipSdk/Baidu/Aip/Face/Face.cs:line 193

**Comment by dogvane** [comment]
我用WebClient组件改写了网络请求功能，现在能调用了。
目前结论是，HttpWebRequest组件要么使用上有瑕疵，要么HttpWebRequest在linux下兼容不好。
建议将组件在linux下做一下兼容性测试，再更新一个版本吧。

**Comment by lams2135** [comment]
Same issue met
